/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perc;

import javax.swing.JOptionPane;

/**
 *
 * @author Anirudh
 */
public class CodeMasters extends javax.swing.JFrame {

    String cppCode ;
    String javaCode ;
    Client client ;
    String teamName ;
    int runsLeft ;
    int score ;
    int remainingTime ;
    CMQObject[] obj ;
    int qId ;
    Thread t ;
    
    
    /**
     * Creates new form CodeMastersList
     */
    public CodeMasters() {
        
        System.out.println("default constructor called");
        
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
  
        runsLeft = 3 ;
        
        cppCode = "#include <cmath>\n" +
                  "#include <cstdio>\n" +
                  "#include <vector>\n" +
                  "#include <iostream>\n" +
                  "#include <algorithm>\n" +
                  "#include <fstream>\n"+
                  "#include <stdlib>\n"+
                  "#include <cstring>\n"+
                  "using namespace std;\n" +
                  "\n" +
                  "\n" +
                  "int main() {\n\n\n" +                
                  "}" ;
        
        javaCode = "import java.io.*;\n" +
                   "import java.util.*;\n" +
                   "import java.text.*;\n" +
                   "import java.math.*;\n" +
                   "import java.util.regex.*;\n" +
                   "\n" +
                   "public class Solution {\n" +
                   "\n" +
                   "\n" +
                   " public static void main(String[] args) {\n\n\n" +        
                   "   }\n\n" +
                   "}" ;
        
        
    }
    
    public CodeMasters(Client client, String teamName, int score , int remaingingTime) {
        
        
        System.out.println("not default constructor called");
    
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
  
        this.client = client ;
        this.teamName = teamName ;
        
        this.remainingTime = remaingingTime ;
        //jLabel6.setText(remaingingTime+"");
        
        runsLeft = 3 ;
        this.score = score ;
        
        cppCode = "#include <cmath>\n" +
                  "#include <cstdio>\n" +
                  "#include <vector>\n" +
                  "#include <iostream>\n" +
                  "#include <algorithm>\n" +
                  "#include <fstream>\n"+
                  "#include <stdlib>\n"+
                  "#include <cstring>\n"+
                  "using namespace std;\n" +
                  "\n" +
                  "\n" +
                  "int main() {\n\n\n" +                
                  "}" ;
        
        javaCode = "import java.io.*;\n" +
                   "import java.util.*;\n" +
                   "import java.text.*;\n" +
                   "import java.math.*;\n" +
                   "import java.util.regex.*;\n" +
                   "\n" +
                   "public class Solution {\n" +
                   "\n" +
                   "\n" +
                   " public static void main(String[] args) {\n\n\n" +        
                   "   }\n\n" +
                   "}" ;
    
        t = new Thread(new Runnable() {
            
            @Override
            public void run() {
            
                try {
                    int i ;
                    for( i=remaingingTime; i>=0; i--)
                    {
                        t.sleep(1000);
                        jLabel6.setText((i/60)+" : "+(i%60));
                    }
                    
                    if( i == 0 ) {
                    
                        jButton1.disable();
                        t.sleep(1000);
                        JOptionPane.showMessageDialog(null,"Quiz Ended");
                        new FinalScore(client, score, client.teamName, 0).setVisible(true);
                        disposer();
                        dispose();
              
                    }
                    
                } catch (InterruptedException ex) {
                        ex.printStackTrace();
                }
            
            
            }
        });
        
        t.start() ;
        
        obj = this.client.getCMQuestions() ;
        
        qId = 0 ;
        
        populate(qId);
        
        
        // add logic of timer 
       // use string to set initial value of timer
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 766));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("     ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 154, 81));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(15);
        jTextArea1.setText("PROBLEM STATEMENT\nINPUT / OUTPUT\nSAMPLE TESTCASE");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, 1346, 230));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 407, 1346, 270));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C++", "Java" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 370, 310, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT CODE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 263, 53));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Question Number : ");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 98, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 98, 47, 18));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1248, 26, 118, 35));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Language : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 370, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/perc/Dark-HD-Wallpapers-1080p.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
        String language =(String) jComboBox1.getSelectedItem() ;
        
        if ( language.equals(new String("C++") ) ) {
        
            jTextArea2.setText(cppCode);
        
        } else {
        
            jTextArea2.setText(javaCode);
        
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

        jTextArea2.setText(cppCode);

    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String code = jTextArea2.getText() ;
        
        String language=(String)jComboBox1.getSelectedItem();
        
        client.sendCodeForSubmitting( Integer.parseInt(jLabel2.getText()) ,code , teamName , language) ;
        
        
        
        //score +=  client.sendCodeForSubmitting( Integer.parseInt(jLabel2.getText()) ,code , teamName ) ;
        
        // jLabel3.setText(score+"") ;
        
        qId++;
        
        populate(qId);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void populate(int qid) {
        
        
        
        if( qId >= 2 ) {

            JOptionPane.showMessageDialog(null,"Quiz Ended");
            new FinalScore(client, score, client.teamName, getSeconds(jLabel6.getText())).setVisible(true);
            this.dispose();

        } else {
        
        jTextArea1.setText("") ;
        
        jLabel2.setText((qId+1)+"");
        jTextArea1.append(obj[qid].ps);
        jTextArea1.append("\n\nINPUT FORMAT :\n");
        jTextArea1.append(obj[qid].ipf+"");
        jTextArea1.append("\n\nOUTPUT FORMAT :\n");
        jTextArea1.append(obj[qid].opf);
        jTextArea1.append("\n\nSAMPLE TESTCASE :\n");
        jTextArea1.append(obj[qid].stc);
    
        }
    
    }
    
    void disposer()
    {
        this.dispose();
    }
    
    
    
    int getSeconds(String timeLeft)
    {
        int min, sec;
        String arr[]=new String[2];
        arr=timeLeft.split("\\:");
        arr[0]=arr[0].trim();
        arr[1]=arr[1].trim();
        min=Integer.parseInt(arr[0]);
        min*=60;
        sec=Integer.parseInt(arr[1])+min;
        return sec;
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CodeMasters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CodeMasters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CodeMasters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CodeMasters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CodeMasters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
